### ISSUE TITLE
Iron Ingots

### ISSUE THREAD

**Issue by DrunkinDonuts** [FireBall1725/LeftBehind-Modpack#10]
cant craft a crowbar...seems putting iron ore chunk from Ex Nihilo in a furnance makes the ingots NBT a different value??

![2018-04-02_11 31 01](https://user-images.githubusercontent.com/37989269/38204846-09689924-366a-11e8-86cf-311bc8469328.png)
![2018-04-02_11 31 26](https://user-images.githubusercontent.com/37989269/38204848-0bc20f8e-366a-11e8-88c1-c905dac9972e.png)

THX

**Comment by DrunkinDonuts** [comment]
I tried the furance, porcelian smeltry, and induction smelter...they all made iron ingots that DID NOT have the minecraft tag.

**Comment by FireBall1725** [comment]
one note, i noticed that the crowbar required a red terracotta brick, but yours looked to be the normal one

![image](https://user-images.githubusercontent.com/727458/38257398-04f88df8-3715-11e8-9b9d-c0a9a59cec5c.png)
vs
![image](https://user-images.githubusercontent.com/727458/38257421-0e623e84-3715-11e8-8f66-eddb3c853259.png)

Also, to turn on full item details, it is F3 + H (i think) that should show you all the item info on hover.

**Comment by AdamBedoui** [comment]
As mentionned by fire, it requires **Red** Terracotta.
For that, you will need to bonemeal the grass, until you obtain a poppy :)

![3](https://user-images.githubusercontent.com/25170558/38342236-0f1c5100-3875-11e8-8966-eb7f895be631.png)

**Comment by FireBall1725** [comment]
@DrunkinDonuts can you confirm that this isn't an issue anymore

**Comment by FireBall1725** [comment]
confirmed with playtest that recipe works, needs to be red terracotta.
