### ISSUE TITLE
Add mod that shows mod names in tooltip

### ISSUE THREAD

**Issue by FireBall1725** [FireBall1725/LeftBehind-Modpack#11]
forget the name of the mod, but i think im using it in a dev env somewhere

**Comment by AdamBedoui** [comment]
I guess it's **Mod Name Tooltip**
Game Version: 1.12.2
![image](https://user-images.githubusercontent.com/25170558/38265874-099cde86-376f-11e8-8f57-f15adc1eee21.png)
https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip

**Comment by FireBall1725** [comment]
added to 0.0.7
