### ISSUE TITLE
mini coal / charcoal mod

### ISSUE THREAD

**Issue by FireBall1725** [FireBall1725/LeftBehind-Modpack#13]
Either make one or use Pickle Tweaks and config the other things out that are not needed

**Comment by AdamBedoui** [comment]
Actually Additions has its item "Tiny Coal"
but adding this mod will require disabling a lot of not needed items

**Comment by FireBall1725** [comment]
@AdamBedoui there is a mod from Kiwifails that does just this, but it isn't for 1.12, so I was going to ask Kiwi if i could update it, or if she was going to update it.

**Comment by FireBall1725** [comment]
https://github.com/kiwifails/MiniCoal/pull/5

**Comment by FireBall1725** [comment]
# #https://github.com/kiwifails/MiniCoal/pull/5

**Comment by FireBall1725** [comment]
added to 0.0.7
