### ISSUE TITLE
Add soul drops from soulsand and sieve

### ISSUE THREAD

**Issue by FireBall1725** [FireBall1725/LeftBehind-Modpack#14]

**Comment by FireBall1725** [comment]
The following is a list of things that are not obtainable

Rotten Flesh
![image](https://user-images.githubusercontent.com/727458/38318150-905f5d8a-37e3-11e8-9f2c-f461b61a2228.png)

Leather & Beef
![image](https://user-images.githubusercontent.com/727458/38318223-b347d2dc-37e3-11e8-9073-9e9dc635711f.png)

Pork
![image](https://user-images.githubusercontent.com/727458/38318242-bcbae21e-37e3-11e8-8a79-a903205c63cd.png)

Eggs and Feathers
![image](https://user-images.githubusercontent.com/727458/38318257-c3ab6a12-37e3-11e8-8414-1b886083b888.png)

Bone and Arrow
![image](https://user-images.githubusercontent.com/727458/38318279-d3532a2c-37e3-11e8-9611-a8fddff7c278.png)

Spider eye
![image](https://user-images.githubusercontent.com/727458/38318357-fb10209c-37e3-11e8-9262-f31086f3406f.png)

Rabbit
![image](https://user-images.githubusercontent.com/727458/38318376-029016d8-37e4-11e8-864d-f8e3f1beb9c9.png)

Blizz
![image](https://user-images.githubusercontent.com/727458/38318435-2885c8ec-37e4-11e8-90c9-ff155f4ed220.png)

Blitz
![image](https://user-images.githubusercontent.com/727458/38318445-302fb49a-37e4-11e8-82e5-9bf56f4f6591.png)

Basalz
![image](https://user-images.githubusercontent.com/727458/38318463-3a757f0c-37e4-11e8-9f35-ea2ec55594bb.png)

Ghast Tear
![image](https://user-images.githubusercontent.com/727458/38318506-516c8cd2-37e4-11e8-8022-83a8cfdc8eda.png)

Wither skeleton skulls
![image](https://user-images.githubusercontent.com/727458/38318529-61be760e-37e4-11e8-9274-4b4b623cb496.png)

**Comment by FireBall1725** [comment]
Maybe i should make a recipe for the Morb

**Comment by FireBall1725** [comment]
Idea goes like this, craft the Morb (1x soul sand + 1x slag + 1x slimeball + 1x enderpearl = 8x morb) then use the morb + ? = morb with the mob in it

**Comment by FireBall1725** [comment]
![image](https://user-images.githubusercontent.com/727458/38331114-33518ea0-3807-11e8-8398-3fd9eca64460.png)
![image](https://user-images.githubusercontent.com/727458/38331123-3b84be58-3807-11e8-8e79-f298579630fa.png)

just need to figure out what to put in the 4 open spots

**Comment by AdamBedoui** [comment]
> Idea goes like this, craft the Morb (1x soul sand + 1x slag + 1x slimeball + 1x enderpearl = 8x morb) then use the morb + ? = morb with the mob in it

Good idea Fire (y)
I wanted to craft an ender pearl seed, but i'm stuck because of the Enderman Chunk..

Just a small remark : We can obtain Blizz rod using the TE compacter, once the player crafted the Blizz Powder ( never used this machine )
I made Blizz Powder using the fluid transposer (with snowball, which i obtained by Glacial Precipitator ), which i used to upgrade the energy cell to signalium

Same goes with Blitz rod (sand instead of snowball)

**Comment by FireBall1725** [comment]
This is going into the next version (0.0.6)

![image](https://user-images.githubusercontent.com/727458/38378478-ab739576-38b2-11e8-8136-01b5bdfd2aaa.png)
![image](https://user-images.githubusercontent.com/727458/38378481-b164f164-38b2-11e8-850e-207dd7cf8976.png)
![image](https://user-images.githubusercontent.com/727458/38378488-b828e064-38b2-11e8-8a40-fd704c5b74ec.png)

I will make recipes for the morbs with mobs using mystical stuff, so you can spawn the physical mob if you need it

**Comment by FireBall1725** [comment]
not going to add all the mobs, but here is what im thinking for some of the mobs

![image](https://user-images.githubusercontent.com/727458/38384519-3bb34efe-38c4-11e8-8c71-f019b3ab66e6.png)

**Comment by FireBall1725** [comment]
![image](https://user-images.githubusercontent.com/727458/38388539-5d721280-38d0-11e8-9b83-6c3cac30acf7.png)

**Comment by FireBall1725** [comment]
added recipes for:
Zombie
Pig Zombie
Pig
Chicken
Cow
Sheep
Slime
Blue Slime
Skeleton
Creeper
Spider
Cave Spider
Rabbit
Guardian
Elder Guardian
Blaze
Ghast
Enderman
Wither Skeleton
Blizz
Blitz
Basalz

Added support for EnderIO Soul Vials as well as Morbs

**Comment by FireBall1725** [comment]
Fixed in 0.0.6

**Comment by AdamBedoui** [comment]
Fire : we still need a recipe to get feathers (chicken essence needs feathers to be crafted)
