### ISSUE TITLE
Alloy Smelter 

### ISSUE THREAD

**Issue by AdamBedoui** [FireBall1725/LeftBehind-Modpack#17]
Hi,
To make the Alloy smelter from EnderIO, we need "Grains of Infinity"
which will require bedrock,  as shown in this picture

![1](https://user-images.githubusercontent.com/25170558/38342028-a37b3d2c-3873-11e8-8755-4cb54f8ee077.png)
![2](https://user-images.githubusercontent.com/25170558/38342031-ab17d39c-3873-11e8-83ab-75a5dbe3a6a9.png)

I suggest tweaking this recipe by replacing the Grains of Infinity by something accessible to us, such as basic capacitors, like it was in the previous versions of EnderIO.

Cordially.

**Comment by FireBall1725** [comment]
It looks like you need them for more than just that
![image](https://user-images.githubusercontent.com/727458/38346337-44de9b12-3849-11e8-96da-8a8e7fe0b8ad.png)

**Comment by AdamBedoui** [comment]
Haha yes indeed xD

Unfortunately EnderIO doesn't seem to be so useful for now ...
Besides, the farming station is not compatible with agricraft, which requires the AgriCraft Farming Station
 from " Ender IO addons".
I looked at the Github repository, and it's not yet upadted to 1.12.2
https://github.com/HenryLoenwind/EnderIOAddons

![image](https://user-images.githubusercontent.com/25170558/38452817-75efdf3a-3a43-11e8-9e64-aa3e0e2a46d9.png)

Are you considering the possibility of removing it from the pack
(even if i still consider it one of the best mods that i ever used ..)

**Comment by FireBall1725** [comment]
so im thinking of 2 solutions for the grains

1. give the user a piece of bedrock, and change how much time it takes for the sag mill to produce grains

2. sieve cobblestone will give you grains

what do you think? 1 or 2 or both?

**Comment by AdamBedoui** [comment]
both ideas are great !
may be hiding a piece of bedrock in one of those crates :D 
i guess it will be better to implement both ! (especially in case if the player lost his bedrock)

**Comment by FireBall1725** [comment]
Added to 0.0.6

![image](https://user-images.githubusercontent.com/727458/38378582-0fa3cb60-38b3-11e8-824a-677e89601577.png)

Will also put 2x bedrock in a crate, hopefully the user won't place it.
