### ISSUE TITLE
Enderman Head

### ISSUE THREAD

**Issue by AdamBedoui** [FireBall1725/LeftBehind-Modpack#18]
Enderman heads are required in quite few recipes related to EnderIO.
We may have to tweak some more recipes.
**EDIT**: I changed the title because i just realized that other mobs heads are craftable once we fixed the [issue related to mob drops](https://github.com/FireBall1725/LeftBehind-Modpack/issues/14) .

![4](https://user-images.githubusercontent.com/25170558/38356543-ebbe260a-38b7-11e8-9d30-f4246ab2eead.png)

**Comment by FireBall1725** [comment]
fixed in 0.0.6

![image](https://user-images.githubusercontent.com/727458/38389358-12c37b4a-38d3-11e8-9d39-6ac87007a549.png)
