### ISSUE TITLE
[Suggestion] Mob spawning mechanic

### ISSUE THREAD

**Issue by AdamBedoui** [FireBall1725/LeftBehind-Modpack#19]
I was looking in JEI, i found an item called Aversion Obelisk (from EnderIO)
The description tells everything about it  (i never used it before)
![5](https://user-images.githubusercontent.com/25170558/38357632-17e24e20-38bb-11e8-9661-31ad356d26c4.png)

TBH, i still don't know how you have managed to stop mobs from spawning , but what if alter the map by putting one or more Aversion Obelisks outside the spaceship (to disable mob spawning in the begining of the game, by default) , and then when the player aquire enough torches, a command bloc removes those Aversion Obelisk, so that mobs may spawn again

**Comment by FireBall1725** [comment]
The reason the mobs don't spawn is it is space, there is a config that lets me make it so mobs spawn, however that won't fix everything, as there are nether mobs and end mobs that still won't spawn.

My goal is to find an alternative to the normal building a dark room skyblock mob farm

**Comment by FireBall1725** [comment]
should be resolved in 0.0.6
