### ISSUE TITLE
Sky Stone

### ISSUE THREAD

**Issue by AdamBedoui** [FireBall1725/LeftBehind-Modpack#20]
I started Applied energestics, and i can't seem to find any way to get "Sky Stone" 
( in odrer to make an ME Controller, but for now i just have a very basic ME system, i just used an energy accepter).

Usually in skyblocks modpacks i use "Sky Stone Dust" ( i get it by sifting dust ) on a wooden barrel with lava to make Sky Stone, but it seems that we need to add this recipe.
Cordially.

**Comment by FireBall1725** [comment]
![image](https://user-images.githubusercontent.com/727458/38383483-7afa95f2-38c1-11e8-959c-af554d7b7147.png)

![image](https://user-images.githubusercontent.com/727458/38383500-86f8fd4e-38c1-11e8-9931-364fd04a639c.png)

Will be fixed in 0.0.6
