### ISSUE TITLE
Carry On Mod / Packing Tape Mod

### ISSUE THREAD

**Issue by AdamBedoui** [FireBall1725/LeftBehind-Modpack#23]
I'm currently cleaning up my base, and it's such a pain to move tons of chests and drawers full of stuff and things...
So I wanna suggest adding one quality of life mod to make things easier for us.
For example : adding the [Carry On Mod ](https://minecraft.curseforge.com/projects/carry-on) or may be the [Packing Tape Mod](https://minecraft.curseforge.com/projects/packing-tape)
Both are available for MC 1.12

Cordially.

**Comment by FireBall1725** [comment]
I will take a look, thank you for the suggestion

**Comment by FireBall1725** [comment]
Added Packing Tape Mod to 0.0.8
