### ISSUE TITLE
Soybean Seeds

### ISSUE THREAD

**Issue by AdamBedoui** [FireBall1725/LeftBehind-Modpack#24]
I'm trying to make a better source of food using Pam's HarvestCraft mod.
The thing is that I can't get Soybean Seeds since there is no jungle biomes in the sky.
Is it possible to add Soybean Seeds drops from sieving dirt ?

(In fact all Pam's seeds are not craftable, this will be such a pain to resolve :( )

Cordially.

**Comment by AdamBedoui** [comment]
Issue resolved. 
Sorry my bad, I totally forgot about the Market block from Pam's HarvestCraft !
I can buy seeds for emeralds.

![2018-04-12_11-05-57](https://user-images.githubusercontent.com/25170558/38671052-49dad9b0-3e42-11e8-99af-00b5a1f5cfb6.png)

**Comment by FireBall1725** [comment]
Closing issue since you found the market block
